In [13]:
import dash                     # pip install dash
from dash.dependencies import Input, Output, State
from dash import dcc
from dash import html
import plotly.express as px     # pip install plotly==5.2.2
import pandas as pd 
import numpy as np
from scipy import stats

In [2]:
df = pd.read_excel("C:\\Users\\Raj-Lenovo\\Desktop\\FORE\\TERM-4\\BDDA\\EU_Superstore_Dataset.xlsx")

In [3]:
df.head()


Row ID         Order ID           Order Date        Dispatch Date  \
0     1.0  ES-2022-1311038  2022-07-02 00:00:00  2022-11-02 00:00:00   
1     2.0  ES-2022-1311038  2022-07-02 00:00:00  2022-11-02 00:00:00   
2     3.0  ES-2022-1311038  2022-07-02 00:00:00  2022-11-02 00:00:00   
3     4.0  ES-2022-1311038  2022-07-02 00:00:00  2022-11-02 00:00:00   
4     5.0  ES-2022-1311038  2022-07-02 00:00:00  2022-11-02 00:00:00   

    Delivery Mode Customer ID   Customer Name    Segment   City  \
0  Standard Class    AS-10045  Aaron Smayling  Corporate  Leeds   
1  Standard Class    AS-10045  Aaron Smayling  Corporate  Leeds   
2  Standard Class    AS-10045  Aaron Smayling  Corporate  Leeds   
3  Standard Class    AS-10045  Aaron Smayling  Corporate  Leeds   
4  Standard Class    AS-10045  Aaron Smayling  Corporate  Leeds   

  State/Province  Country/Region Region       Product ID         Category  \
0        England  United Kingdom  North  OFF-ST-10000988  Office Supplies   
1        England  United Kingdom  North  TEC-AC-10004144       Technology   
2        England  United Kingdom  North  OFF-LA-10001915  Office Supplies   
3        England  United Kingdom  North  OFF-ST-10004550  Office Supplies   
4        England  United Kingdom  North  TEC-AC-10004068       Technology   

  Sub-Category                                Product Name   Sales  Quantity  \
0      Storage                      Fellowes Folders, Blue   79.20       3.0   
1  Accessories           SanDisk Numeric Keypad, Bluetooth  388.92       7.0   
2       Labels  Avery Legal Exhibit Labels, 5000 Label Set   35.19       3.0   
3      Storage                Fellowes Folders, Wire Frame   50.94       2.0   
4  Accessories                    Memorex Memory Card, USB  307.44       3.0   

   Discount  Profit  
0       0.0   39.60  
1       0.0    0.00  
2       0.0   16.11  
3       0.0   13.20  
4       0.0   73.71

In [6]:
df.describe()


Row ID         Sales      Quantity      Discount        Profit
count  10000.00000  10000.000000  10000.000000  10000.000000  10000.000000
mean    5000.50000    293.808906      3.777300      0.103105     37.282974
std     2886.89568    486.055635      2.203268      0.174782    178.100384
min        1.00000      2.955000      1.000000      0.000000  -3059.820000
25%     2500.75000     49.462500      2.000000      0.000000      1.320000
50%     5000.50000    119.355000      3.000000      0.000000     14.220000
75%     7500.25000    320.708625      5.000000      0.100000     48.510000
max    10000.00000   7958.580000     14.000000      0.850000   3979.080000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Row ID          10000 non-null  float64
 1   Order ID        10000 non-null  object 
 2   Order Date      10000 non-null  object 
 3   Dispatch Date   10000 non-null  object 
 4   Delivery Mode   10000 non-null  object 
 5   Customer ID     10000 non-null  object 
 6   Customer Name   10000 non-null  object 
 7   Segment         10000 non-null  object 
 8   City            10000 non-null  object 
 9   State/Province  10000 non-null  object 
 10  Country/Region  10000 non-null  object 
 11  Region          10000 non-null  object 
 12  Product ID      10000 non-null  object 
 13  Category        10000 non-null  object 
 14  Sub-Category    10000 non-null  object 
 15  Product Name    10000 non-null  object 
 16  Sales           10000 non-null  float64
 17  Quantity        10000 non-null  

In [21]:
z = np.abs(stats.zscore(df['Sales']))
print(z)

threshold = 3
 
# Position of the outlier
print(np.where(z > 3))

0       0.441554
1       0.195689
2       0.532103
3       0.499698
4       0.028046
          ...   
9995    0.481428
9996    0.590803
9997    0.405630
9998    0.430304
9999    0.291193
Name: Sales, Length: 10000, dtype: float64
(array([   8,   11,   13,   43,   70,   82,  109,  113,  130,  147,  155,
        206,  289,  325,  346,  353,  375,  450,  500,  575,  689,  705,
        709,  712,  720,  773,  848,  874,  922,  927,  941,  951, 1036,
       1087, 1316, 1350, 1362, 1531, 1584, 1696, 1724, 1737, 1740, 1756,
       1774, 1778, 1823, 1826, 1839, 1859, 1861, 1866, 1875, 1926, 1935,
       1947, 2083, 2088, 2118, 2154, 2178, 2211, 2377, 2473, 2479, 2669,
       2713, 2749, 2819, 2883, 2901, 2933, 3004, 3030, 3096, 3184, 3202,
       3229, 3233, 3265, 3362, 3379, 3410, 3419, 3484, 3552, 3596, 3716,
       3726, 3730, 3775, 3805, 3848, 3914, 3919, 3925, 3975, 3980, 4016,
       4028, 4085, 4110, 4313, 4452, 4523, 4526, 4637, 4748, 4837, 4848,
       4871, 4930, 5064, 5085, 5094, 51

In [23]:
z = np.abs(stats.zscore(df['Discount']))
print(z)

threshold = 3
 
# Position of the outlier
print(np.where(z > 3))

0       0.589937
1       0.589937
2       0.589937
3       0.589937
4       0.589937
          ...   
9995    0.589937
9996    0.589937
9997    0.589937
9998    0.589937
9999    0.589937
Name: Discount, Length: 10000, dtype: float64
(array([1704, 1764, 1833, 2085, 2334, 2389, 3296, 3534, 3664, 3874, 4107,
       4318, 4786, 5040, 5940, 6139, 6257, 6260, 6472, 7578, 8163, 8633,
       8689, 9006, 9530, 9657, 9736, 9886, 9930], dtype=int64),)


In [24]:
z = np.abs(stats.zscore(df['Quantity']))
print(z)

threshold = 3
 
# Position of the outlier
print(np.where(z > 3))

0       0.352812
1       1.462764
2       0.352812
3       0.806706
4       0.352812
          ...   
9995    0.806706
9996    1.260600
9997    1.008870
9998    1.462764
9999    1.008870
Name: Quantity, Length: 10000, dtype: float64
(array([ 104,  193,  219,  325,  346,  420,  451,  600,  705,  890,  991,
       1094, 1201, 1433, 1582, 1603, 1716, 1774, 1916, 1951, 1976, 2083,
       2153, 2389, 2448, 2545, 2626, 2693, 2738, 2749, 3013, 3265, 3295,
       3509, 3523, 3595, 3644, 3654, 3775, 3802, 3971, 3991, 4110, 4214,
       4288, 4338, 4348, 4350, 4427, 4432, 4446, 4487, 4541, 4616, 4748,
       4821, 4848, 4908, 4910, 4997, 5085, 5206, 5366, 5394, 5451, 5512,
       5635, 5665, 5776, 5780, 5818, 5890, 5944, 5979, 5982, 6004, 6014,
       6161, 6292, 6320, 6498, 6505, 6508, 6539, 6567, 6730, 6750, 6785,
       6944, 6949, 7088, 7598, 7609, 8039, 8097, 8130, 8207, 8459, 8485,
       8518, 8557, 8562, 8636, 8947, 8972, 9011, 9065, 9125, 9136, 9184,
       9232, 9288, 9387, 9507, 9574,

In [25]:
z = np.abs(stats.zscore(df['Profit']))
print(z)

threshold = 3
 
# Position of the outlier
print(np.where(z > 3))

0       0.013010
1       0.209347
2       0.118888
3       0.135228
4       0.204541
          ...   
9995    0.075259
9996    0.206147
9997    0.046622
9998    1.032318
9999    0.072643
Name: Profit, Length: 10000, dtype: float64
(array([   8,   11,   13,  113,  147,  155,  206,  325,  345,  346,  353,
        375,  450,  485,  575,  705,  709,  712,  722,  848,  925,  927,
        941, 1007, 1051, 1087, 1225, 1316, 1350, 1475, 1494, 1584, 1653,
       1696, 1704, 1705, 1740, 1756, 1769, 1774, 1778, 1781, 1826, 1875,
       1934, 1935, 2088, 2118, 2146, 2154, 2178, 2204, 2211, 2332, 2358,
       2377, 2389, 2473, 2500, 2669, 2688, 2713, 2729, 2749, 2819, 2872,
       2898, 2901, 3004, 3096, 3184, 3202, 3228, 3233, 3265, 3283, 3296,
       3410, 3419, 3494, 3499, 3534, 3552, 3664, 3690, 3703, 3726, 3739,
       3742, 3775, 3789, 3801, 3805, 3848, 3874, 3925, 3975, 4016, 4107,
       4110, 4118, 4200, 4289, 4412, 4499, 4523, 4535, 4637, 4748, 4786,
       4837, 4848, 5064, 5085, 5119, 5

In [4]:
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.layout = html.Div([
    html.H1("Analytics Dashboard of EU Superstore Dataset (Dash Plotly)", style={"textAlign":"center"}),
    html.Hr(),
    html.P("Choose Product Category:"),
    html.Div(html.Div([
        dcc.Dropdown(id='category-type', clearable=False,
                     value="Office Supplies",
                     options=[{'label': x, 'value': x} for x in
                              df["Category"].unique()]),
    ],className="two columns"),className="row"),

    html.Div(id="output-div", children=[]),
])
@app.callback(Output(component_id="output-div", component_property="children"),
              Input(component_id="category-type", component_property="value"),
)
def make_graphs(category_chosen):
   
    # HISTOGRAM
    df_hist = df[df["Category"]==category_chosen]
    fig_hist = px.histogram(df_hist, x="Sub-Category")
    fig_hist.update_xaxes(categoryorder="total descending")
    # STRIP CHART
    fig_strip = px.strip(df_hist, x="Quantity", y="Sub-Category")

    # SUNBURST
    df_sburst = df.dropna(subset=['Category'])
    df_sburst = df_sburst[df_sburst["Sub-Category"].isin(["Labels", "Appliances", "Art", "Phones", "Machines"])]
    fig_sunburst = px.sunburst(df_sburst, path=["Category", "Sub-Category", "Quantity"])

    # Empirical Cumulative Distribution
    df_ecdf = df[df["Category"].isin(["Office Supplies","Technology"])]
    fig_ecdf = px.ecdf(df_ecdf, x="Sales", color="Category")

    # LINE CHART
    df_line = df
    df_line = df_line.groupby(
        ["Dispatch Date", "Category"]).size().reset_index(name="count")
    df_line.head()
    fig_line = px.line(df_line, x="Dispatch Date", y="count",
                       color="Category", markers=True)

    return [
        html.Div([
            html.Div([dcc.Graph(figure=fig_hist)], className="six columns"),
            html.Div([dcc.Graph(figure=fig_strip)], className="six columns"),
        ], className="row"),
        html.H2("All Categories", style={"textAlign":"center"}),
        html.Hr(),
        html.Div([
            html.Div([dcc.Graph(figure=fig_sunburst)], className="six columns"),
            html.Div([dcc.Graph(figure=fig_ecdf)], className="six columns"),
        ], className="row"),
        html.Div([
            html.Div([dcc.Graph(figure=fig_line)], className="twelve columns"),
        ], className="row"),
    ]


In [ ]:
if __name__ == '__main__':
    app.run_server(debug=False)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [16/Aug/2022 17:40:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:40:04] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:40:04] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:40:04] "GET /_favicon.ico?v=2.6.1 HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:40:04] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:40:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:40:05] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:40:05] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:42:23] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:42:27] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2022 17:43:05] "POST /_dash-update-component HTTP/1.1" 